"""add sys_announcements table

Revision ID: 466284c736b7
Revises: d2120e3508cd
Create Date: 2026-09-16 13:11:11.152727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466284c736b7'
down_revision: Union[str, Sequence[str], None] = 'd2120e3508cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_announcements',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='正文（纯文本）'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='类型：notice=通知 / announcement=公告（字典 sys_announce_type）'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态：0 草稿 / 1 已发布 / 2 已下线'),
    sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶（置顶优先展示）'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='过期时间，空 = 永不过期'),
    sa.Column('publish_time', sa.DateTime(), nullable=True, comment='发布时间（发布动作时写入）'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True, comment='发布人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_announcements_is_top'), 'sys_announcements', ['is_top'], unique=False)
    op.create_index(op.f('ix_sys_announcements_publish_time'), 'sys_announcements', ['publish_time'], unique=False)
    op.create_index(op.f('ix_sys_announcements_status'), 'sys_announcements', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_announcements_status'), table_name='sys_announcements')
    op.drop_index(op.f('ix_sys_announcements_publish_time'), table_name='sys_announcements')
    op.drop_index(op.f('ix_sys_announcements_is_top'), table_name='sys_announcements')
    op.drop_table('sys_announcements')
    # ### end Alembic commands ###
