"""add files table

Revision ID: 7c4073415894
Revises: 5ce0aa739071
Create Date: 2026-09-14 12:03:51.895973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4073415894'
down_revision: Union[str, Sequence[str], None] = '5ce0aa739071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_created_by'), 'files', ['created_by'], unique=False)
    op.create_index(op.f('ix_files_source'), 'files', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_source'), table_name='files')
    op.drop_index(op.f('ix_files_created_by'), table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
