"""add sys_configs table

Revision ID: d2120e3508cd
Revises: f53da704f186
Create Date: 2026-09-16 12:19:37.903471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2120e3508cd'
down_revision: Union[str, Sequence[str], None] = 'f53da704f186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_configs',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False, comment='配置键，如 site_name'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值（统一字符串）'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='值类型标注：string/int/bool'),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_configs_key'), 'sys_configs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_configs_key'), table_name='sys_configs')
    op.drop_table('sys_configs')
    # ### end Alembic commands ###
