"""add dict_types and dict_items

Revision ID: f53da704f186
Revises: 7c4073415894
Create Date: 2026-09-14 16:47:08.384052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53da704f186'
down_revision: Union[str, Sequence[str], None] = '7c4073415894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_types',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='字典名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='字典类型编码，如 file_source'),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dict_types_type'), 'dict_types', ['type'], unique=True)
    op.create_table('dict_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False, comment='显示文案'),
    sa.Column('value', sa.String(length=50), nullable=False, comment='存储值'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='排序，越小越靠前'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认'),
    sa.Column('status', sa.Integer(), nullable=False, comment='1启用 0禁用'),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['dict_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dict_items_type_id'), 'dict_items', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dict_items_type_id'), table_name='dict_items')
    op.drop_table('dict_items')
    op.drop_index(op.f('ix_dict_types_type'), table_name='dict_types')
    op.drop_table('dict_types')
    # ### end Alembic commands ###
